blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/bniladridas/jarvis-assistant/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/bniladridas/jarvis-assistant/tree/main/docs
    about: Check our documentation first.