name: Dependency Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dependency Review
        uses: actions/dependency-review-action@v2